In [2]:
from sklearn.preprocessing import LabelEncoder  # for one hot encoding

In [3]:
from numpy import *
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [4]:
data=pd.read_csv(r'C:\Users\Brij\Desktop\Python for data science\2019.csv')
data1=data.copy()

In [5]:
data1.columns

Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='object')

In [6]:
data1['Overall rank']=data1['Overall rank'].astype('float64')

In [7]:
X=data1.drop(['Overall rank','Country or region'],axis=1).values
y=data1['Overall rank'].values

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [9]:
reg=LinearRegression()

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [11]:
reg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [18]:
prediction=reg.predict(X_test)

In [23]:
coeff_df = pd.DataFrame(reg.coef_)

In [24]:
coeff_df

           0
0 -45.797490
1  -1.845656
2   2.822664
3  -1.015374
4  -0.408587
5   1.307092
6   2.076652

In [25]:
from sklearn.metrics import accuracy_score

In [28]:
df = pd.DataFrame({'Actual': y_test, 'Predicted': prediction})
df

    Actual   Predicted
0    118.0  111.846546
1     76.0   73.456077
2     52.0   46.967261
3     32.0   32.462274
4     36.0   34.155003
5     41.0   46.463078
6     15.0    5.262990
7    110.0  104.580499
8     54.0   47.229959
9    147.0  156.867968
10   151.0  165.775936
11    79.0   73.176471
12    93.0   77.993238
13    91.0   79.906736
14    90.0   79.883079
15     6.0  -14.777218
16   124.0  110.205074
17    17.0    5.706608
18    20.0    4.445151
19    30.0   28.887557
20    57.0   50.884296
21   144.0  147.003833
22   143.0  138.286180
23   100.0   98.164805
24    94.0   82.942019
25    70.0   62.712621
26    95.0   93.181444
27    43.0   38.545180
28   123.0  117.770861
29    45.0   43.605557
30   106.0  103.635962
31   139.0  129.412603
32    67.0   60.794662
33    34.0   41.002600
34   142.0  137.539323
35    60.0   55.568681
36   128.0  119.715518
37   132.0  120.454987
38   149.0  158.068037
39   126.0  113.405620
40    59.0   53.328588
41    29.0   27.814520
42   125.0  114.297052
43   112.0  110.796915
44    55.0   51.767305
45    18.0    6.383824
46    74.0   72.285103

In [31]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, prediction))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, prediction))  
print('Root Mean Squared Error:',sqrt(metrics.mean_squared_error(y_test, prediction)))

Mean Absolute Error: 7.030320649907241
Mean Squared Error: 70.87633471763259
Root Mean Squared Error: 8.41880839059974

In [32]:
data1.describe()

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,78.500000,5.407096,0.905147,1.208814,0.725244,0.392571,0.184846,0.110603
std,45.177428,1.113120,0.398389,0.299191,0.242124,0.143289,0.095254,0.094538
min,1.000000,2.853000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.750000,4.544500,0.602750,1.055750,0.547750,0.308000,0.108750,0.047000
50%,78.500000,5.379500,0.960000,1.271500,0.789000,0.417000,0.177500,0.085500
75%,117.250000,6.184500,1.232500,1.452500,0.881750,0.507250,0.248250,0.141250
max,156.000000,7.769000,1.684000,1.624000,1.141000,0.631000,0.566000,0.453000

In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
confusion_matrix(y_test,prediction)

ValueError: Classification metrics can't handle a mix of multiclass and continuous targets